version: '3.8'

services:
  app:
    image: ashishdevops1989/user-info-service:0.0.1
    ports:
      - "9092:9092"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/userdb  # Use MySQL instead of PostgreSQL
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect  # MySQL dialect
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
