version: '3'
services:
  eureka-service:
    image: ashishdevops1989/eureka-service:29
    container_name: eureka-service-container
    ports:
      - "8761:8761"
    networks:
      - mypostgresnetwork

  postgres-container:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: userdb
    networks:
      - mypostgresnetwork

  user-info-service:
    image: ashishdevops1989/user-info-service:36
    container_name: user-info-service-container
    ports:
      - "9096:9096"
    networks:
      - mypostgresnetwork

networks:
  mypostgresnetwork:
    driver: bridge
