version: '3'
services:
  eureka-service:
    image: ashishdevops1989/eureka-service:29
    container_name: eureka-service-container
    ports:
      - "8761:8761"
    networks:
      - mymysqlnetwork

  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb  # Create a database named 'userdb'
      MYSQL_USER: root  # Create a user 'root'
      MYSQL_PASSWORD: root  # Set password for the user 'root'
    ports:
      - "3306:3306"  # Expose MySQL on port 3306
    networks:
      - mymysqlnetwork

  user-info-service:
    image: ashishdevops1989/user-info-service:0.0.4
    container_name: user-info-service-container
    ports:
      - "9096:9096"
    networks:
      - mymysqlnetwork

networks:
  mymysqlnetwork:
    driver: bridge
