version: '3.8'

services:
  user-info-service:
    image: ashishdevops1989/user-info-service:latest
    ports:
      - "9096:9096"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/userdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql
    networks:
      - user-service-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userdb
    ports:
      - "3306:3306"
    networks:
      - user-service-network

networks:
  user-service-network:
    driver: bridge
