eureka:
  instance:
    preferIpAddress: true
    hostname: user-info-service-container  # (Optional) You can set this explicitly, but prefer-ip-address should be enough
  client:
    service-url:
      defaultZone: http://eureka-service-container:8761/eureka/  # Eureka URL with container name
      # defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka  # Uncomment if using Kubernetes

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres  # Use the service name 'postgres' as hostname
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
