eureka:
  instance:
    preferIpAddress: true
    hostname: user-info-service-container  # (Optional) You can set this explicitly, but prefer-ip-address should be enough
  client:
    service-url:
      defaultZone: http://eureka-service-container:8761/eureka/  # Eureka URL with container name

spring:
  datasource:
    url: jdbc:postgresql://172.18.0.2:5432/postgres  # Use the PostgreSQL container's IP address or container name
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update  # Automatically updates the database schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Use the PostgreSQL dialect for Hibernate
    show-sql: true  # Show SQL statements in logs

# Uncomment and use this for Kubernetes scenario, if applicable:
# defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka  # Uncomment if using Kubernetes
