spring:
  datasource:
    url: jdbc:postgresql://172.18.0.2:5432/postgres  # Use the container name in Docker network
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update  # Automatically updates the database schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Use the PostgreSQL dialect for Hibernate
    flyway:
    enabled: false    
    show-sql: true  # Show SQL statements in logs

eureka:
  instance:
    preferIpAddress: true
    hostname: user-info-service-container  # Set the hostname to the service container name
  client:
    service-url:
      defaultZone: http://eureka-service-container:8761/eureka/  # Eureka URL with container name
